In [1]:
import tensorflow as tf
from  infer import Inference

##构造数据
#构造embedding特征数据
input_data_1 = tf.random.uniform(shape=(10, ), minval=0, maxval=10000, dtype=tf.float32)
input_data_2 = tf.random.uniform(shape=(10, ), minval=0, maxval=10000, dtype=tf.float32) 
input_data_3 = tf.random.uniform(shape=(10, ), minval=0, maxval=10000, dtype=tf.float32)
input_data_4 = tf.random.uniform(shape=(10, ), minval=0, maxval=10000, dtype=tf.float32)
#构造tags特征
input_data_5 = tf.random.normal(shape=(10, 173))  

##获取推理器
serve_signature_infer, extract_features_signature_infer = Inference().get_infer()  #预测结果推理器和特征推理器




['serving_default', 'predict', 'extract_features']


In [2]:
#预测结果推理器（分类和回归）
serve_signature_infer

<ConcreteFunction (*, genres: TensorSpec(shape=(None,), dtype=tf.float32, name='genres'), item_id: TensorSpec(shape=(None,), dtype=tf.float32, name='item_id'), itemid_seq: TensorSpec(shape=(None,), dtype=tf.float32, name='itemid_seq'), tags: TensorSpec(shape=(None, 173), dtype=tf.float32, name='tags'), user_id: TensorSpec(shape=(None,), dtype=tf.float32, name='user_id')) -> Dict[['output_1', TensorSpec(shape=(None, 6), dtype=tf.float32, name='output_1')], ['output_0', TensorSpec(shape=(None, 1), dtype=tf.float32, name='output_0')]] at 0x1217C9474D0>

In [3]:
#特征推理器
extract_features_signature_infer

<ConcreteFunction (*, genres: TensorSpec(shape=(None,), dtype=tf.float32, name='genres'), item_id: TensorSpec(shape=(None,), dtype=tf.float32, name='item_id'), itemid_seq: TensorSpec(shape=(None,), dtype=tf.float32, name='itemid_seq'), tags: TensorSpec(shape=(None, 173), dtype=tf.float32, name='tags'), user_id: TensorSpec(shape=(None,), dtype=tf.float32, name='user_id')) -> Dict[['output_0', TensorSpec(shape=(None, 64), dtype=tf.float32, name='output_0')]] at 0x1217CAB29D0>

In [4]:

predict_output = serve_signature_infer(user_id=input_data_1, item_id=input_data_2,genres=input_data_3,itemid_seq=input_data_4,tags=input_data_5)  
predict_output

{'output_1': <tf.Tensor: shape=(10, 6), dtype=float32, numpy=
 array([[ -7.893222  ,   3.1209369 ,   2.900347  ,   2.5265996 ,
          -1.1640612 ,  -0.7942321 ],
        [ -8.161081  ,   3.2906494 ,   1.9400684 ,   2.8585227 ,
          -1.4358225 ,  -1.1610829 ],
        [ -6.084412  ,   1.8153973 ,   2.090728  ,   2.8138297 ,
          -0.29414454,  -0.27427825],
        [ -6.934083  ,   2.907183  ,   2.4450428 ,   2.405222  ,
          -0.28654632,  -1.6062192 ],
        [ -6.094262  ,   2.5209715 ,   3.0282304 ,   1.6831329 ,
           0.14647172,  -0.8578907 ],
        [ -5.0272903 ,   1.3029044 ,   1.5245527 ,   1.4304826 ,
           0.68861204,  -0.20422277],
        [ -7.6440587 ,   2.2514422 ,   3.1275299 ,   2.392187  ,
           0.06000981,  -1.7224426 ],
        [ -8.590824  ,   4.5803614 ,   3.4224672 ,   3.5813367 ,
          -0.5333556 ,  -1.8891264 ],
        [-11.921427  ,   4.8221173 ,   5.084543  ,   3.2280989 ,
           0.8587851 ,  -2.1708152 ],
        [ -

In [5]:

#取rating分类预测结果
lable_predictions = tf.argmax(predict_output["output_1"], axis=1)  
lable_predictions

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([1, 1, 3, 1, 2, 2, 2, 1, 2, 1], dtype=int64)>

In [6]:
#取rating回归预测结果
score_predictions = predict_output["output_0"] 
score_predictions

<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[ 8.348099 ],
       [ 8.49879  ],
       [ 7.0811806],
       [ 7.6215014],
       [ 6.915235 ],
       [ 4.7862496],
       [ 8.639514 ],
       [10.461766 ],
       [11.087241 ],
       [ 8.456937 ]], dtype=float32)>

In [8]:
## 取特征
feature_output = extract_features_signature_infer(user_id=input_data_1, item_id=input_data_2,genres=input_data_3,itemid_seq=input_data_4,tags=input_data_5)  
feature_output["output_0"]

<tf.Tensor: shape=(10, 64), dtype=float32, numpy=
array([[0.        , 1.1371208 , 0.6498819 , 1.0154912 , 0.16758436,
        3.5343137 , 0.        , 0.        , 0.        , 0.        ,
        0.3907062 , 0.        , 1.5743604 , 2.056076  , 1.6501552 ,
        2.8891084 , 0.05274589, 0.14747739, 1.2397166 , 0.23254958,
        1.652113  , 1.9592868 , 0.        , 0.        , 0.5195936 ,
        0.        , 0.        , 0.        , 3.8896143 , 1.6482294 ,
        0.5785287 , 0.        , 0.        , 2.598405  , 0.        ,
        0.        , 0.83872354, 0.        , 0.        , 0.        ,
        3.2108815 , 1.6519955 , 0.        , 0.5796882 , 1.330103  ,
        0.        , 0.        , 1.5135818 , 0.        , 2.2325864 ,
        0.        , 2.8915133 , 0.9017381 , 0.        , 0.        ,
        0.        , 1.5313336 , 2.0290937 , 0.        , 0.9027848 ,
        0.3600076 , 0.        , 0.837502  , 3.045705  ],
       [0.        , 1.6771126 , 0.        , 0.        , 0.        ,
        2