In [1]:
import sys
sys.path.append('d://the-recommender/DNN_for_YouTube_Recommendations')

from  sample import ml1m_sample_tfrecord
from datasets.ml1m_dataset import Ml1mDataset 


In [2]:
##初始化参数。在main.py中使用argparse包接收解析参数，此处为了方便在jupyter中演示，将参数放在字典中。
parsed_args = {}
#解析dataset参数
parsed_args["data_path"] =  'd://the-recommender/DNN_for_YouTube_Recommendations/datasets/ml-1m/'
parsed_args["users_file"] =  'users.dat'
parsed_args["ratings_file"] =  'ratings.dat' 
parsed_args["movies_file"] =  'movies.dat'
parsed_args["sep"] =  '::'
parsed_args["header"] =  None

#解析样本参数
parsed_args["sample_output_file"] =  'd://the-recommender/DNN_for_YouTube_Recommendations/sample/__TFRecord/train.tfrecord' 

#解析模型保存参数
parsed_args["export_path"] =  'd://the-recommender/DNN_for_YouTube_Recommendations/SAVEDMODELS/savedmodel/default_signature_with_multiple_input_output'
parsed_args["export_path_multi"] = 'd://the-recommender/DNN_for_YouTube_Recommendations/SAVEDMODELS/savedmodel/multi_signature_with_multiple_input_output'

#解析特征hash参数
parsed_args["userid_hash_nums"] = 10000
parsed_args["itemid_hash_nums"] = 10000
parsed_args["zipid_hash_nums"] = 10000
parsed_args["gender_hash_nums"] = 10
parsed_args["age_hash_nums"] = 100
parsed_args["occupation_hash_nums"] = 100
parsed_args["seqlen_hash_nums"] = 100
parsed_args["hash_salt"] = 1024
parsed_args["vocab_size"] = 1000
parsed_args["seq_len"] = 5

#解析模型网络结构参数
parsed_args["userid_input_dim"] = 1
parsed_args["movieid_input_dim"] = 1
parsed_args["rated_movies_lastN_input_dim"] = 5
parsed_args["genres_input_dim"] = 6
parsed_args["zip_id_input_dim"] = 1
parsed_args["num_ratings"] = 6 
parsed_args["dense_size"] = 256    
parsed_args["embedding_out_dim"] = 64

#解析模型训练参数
parsed_args["batch_size"] = 64
parsed_args["epochs"] = 20 
parsed_args["validation_split"] = 0.2       
parsed_args["score_loss_weight"] = 1
parsed_args["rating_loss_weight"] = 1 
parsed_args["learning_rate"] = 1e-3

In [4]:
#加载数据集
data_loader = Ml1mDataset()
data_X, data_y = data_loader.load_ml1m(parsed_args)

In [5]:
data_X.shape

(1000209, 9)

In [6]:
data_y.shape

(1000209, 1)

In [7]:
#从原始数据集构造样本,并转换为tfrecord格式
sample_num = 10000
train_dataset = ml1m_sample_tfrecord.Ml1mTFRecordSample().tfrecord_sample(data_X[:sample_num], data_y[:sample_num], True, parsed_args) 


In [8]:
#查看样本。注意，新构造了不定长序列特征itemid_lastN
sample_x, sample_y = next(iter(train_dataset))  
sample_x

{'user_id': <tf.Tensor: shape=(), dtype=int64, numpy=1>,
 'item_id': <tf.Tensor: shape=(), dtype=int64, numpy=48>,
 'timestamp': <tf.Tensor: shape=(), dtype=int64, numpy=978824351>,
 'title': <tf.Tensor: shape=(), dtype=string, numpy=b'Pocahontas (1995)'>,
 'genres': <tf.Tensor: shape=(), dtype=string, numpy=b"Animation|Children's|Musical|Romance">,
 'gender': <tf.Tensor: shape=(), dtype=string, numpy=b'F'>,
 'age': <tf.Tensor: shape=(), dtype=int64, numpy=1>,
 'occupation': <tf.Tensor: shape=(), dtype=int64, numpy=10>,
 'zip': <tf.Tensor: shape=(), dtype=string, numpy=b'48067'>,
 'itemid_lastN': <tf.Tensor: shape=(), dtype=string, numpy=b'48|1907|783|1|527'>,
 'itemid_lastN_len': <tf.Tensor: shape=(), dtype=int64, numpy=5>}

In [9]:
sample_y

{'rating': <tf.Tensor: shape=(), dtype=int64, numpy=5>}

In [10]:
# 使用for循环遍历Dataset  
for feature_element, label_element in train_dataset:  
    print("Feature:", feature_element)  
    print("Label:", label_element)
    #print(type(label_element["rating"]),label_element["rating"])
    #print(label_element["rating"].numpy())
    break


Feature: {'user_id': <tf.Tensor: shape=(), dtype=int64, numpy=1>, 'item_id': <tf.Tensor: shape=(), dtype=int64, numpy=48>, 'timestamp': <tf.Tensor: shape=(), dtype=int64, numpy=978824351>, 'title': <tf.Tensor: shape=(), dtype=string, numpy=b'Pocahontas (1995)'>, 'genres': <tf.Tensor: shape=(), dtype=string, numpy=b"Animation|Children's|Musical|Romance">, 'gender': <tf.Tensor: shape=(), dtype=string, numpy=b'F'>, 'age': <tf.Tensor: shape=(), dtype=int64, numpy=1>, 'occupation': <tf.Tensor: shape=(), dtype=int64, numpy=10>, 'zip': <tf.Tensor: shape=(), dtype=string, numpy=b'48067'>, 'itemid_lastN': <tf.Tensor: shape=(), dtype=string, numpy=b'48|1907|783|1|527'>, 'itemid_lastN_len': <tf.Tensor: shape=(), dtype=int64, numpy=5>}
Label: {'rating': <tf.Tensor: shape=(), dtype=int64, numpy=5>}
