In [1]:
import sys
sys.path.append('d://the-recommender/DNN_for_YouTube_Recommendations')

from sample import ml1m_sample
from  sample import ml1m_sample_tfrecord

sample_x, sample_y = ml1m_sample.Ml1mSample().ranking_sample()


In [2]:
sample_x.head()

user_id  item_id  timestamp                                title  \
0        1       48  978824351                    Pocahontas (1995)   
1        1     1907  978824330                         Mulan (1998)   
2        1      783  978824291  Hunchback of Notre Dame, The (1996)   
3        1        1  978824268                     Toy Story (1995)   
4        1      527  978824195              Schindler's List (1993)   

                                 genres gender  age  occupation    zip  \
0  Animation|Children's|Musical|Romance      F    1          10  48067   
1                  Animation|Children's      F    1          10  48067   
2          Animation|Children's|Musical      F    1          10  48067   
3           Animation|Children's|Comedy      F    1          10  48067   
4                             Drama|War      F    1          10  48067   

          itemid_seq  itemid_seq_len  
0  48|1907|783|1|527               5  
1  48|1907|783|1|527               5  
2  48|1907|783|1|527               5  
3  48|1907|783|1|527               5  
4  48|1907|783|1|527               5

In [3]:
sample_x.shape

(471163, 11)

In [4]:
type(sample_x)

pandas.core.frame.DataFrame

In [5]:
sample_y.head()

rating
0       5
1       4
2       4
3       5
4       5

In [6]:
sample_x.shape

(471163, 11)

In [7]:
type(sample_y)

pandas.core.frame.DataFrame

In [8]:
#构造tfrecord样本
train_dataset = ml1m_sample_tfrecord.Ml1mTFRecordSample().tfrecord_sample(sample_x, sample_y, True)
train_dataset

<_ParallelMapDataset element_spec=({'user_id': TensorSpec(shape=(), dtype=tf.int64, name=None), 'item_id': TensorSpec(shape=(), dtype=tf.int64, name=None), 'timestamp': TensorSpec(shape=(), dtype=tf.int64, name=None), 'title': TensorSpec(shape=(), dtype=tf.string, name=None), 'genres': TensorSpec(shape=(), dtype=tf.string, name=None), 'gender': TensorSpec(shape=(), dtype=tf.string, name=None), 'age': TensorSpec(shape=(), dtype=tf.int64, name=None), 'occupation': TensorSpec(shape=(), dtype=tf.int64, name=None), 'zip': TensorSpec(shape=(), dtype=tf.string, name=None), 'itemid_seq': TensorSpec(shape=(), dtype=tf.string, name=None), 'itemid_seq_len': TensorSpec(shape=(), dtype=tf.int64, name=None)}, {'rating': TensorSpec(shape=(), dtype=tf.int64, name=None)})>

In [9]:
sample_image, sample_label = next(iter(train_dataset))  #model.fit(train_dataset, epochs=10)
sample_image

{'user_id': <tf.Tensor: shape=(), dtype=int64, numpy=1>,
 'item_id': <tf.Tensor: shape=(), dtype=int64, numpy=48>,
 'timestamp': <tf.Tensor: shape=(), dtype=int64, numpy=978824351>,
 'title': <tf.Tensor: shape=(), dtype=string, numpy=b'Pocahontas (1995)'>,
 'genres': <tf.Tensor: shape=(), dtype=string, numpy=b"Animation|Children's|Musical|Romance">,
 'gender': <tf.Tensor: shape=(), dtype=string, numpy=b'F'>,
 'age': <tf.Tensor: shape=(), dtype=int64, numpy=1>,
 'occupation': <tf.Tensor: shape=(), dtype=int64, numpy=10>,
 'zip': <tf.Tensor: shape=(), dtype=string, numpy=b'48067'>,
 'itemid_seq': <tf.Tensor: shape=(), dtype=string, numpy=b'48|1907|783|1|527'>,
 'itemid_seq_len': <tf.Tensor: shape=(), dtype=int64, numpy=5>}

In [10]:
sample_label

{'rating': <tf.Tensor: shape=(), dtype=int64, numpy=5>}

In [15]:
# 使用for循环遍历Dataset  
for input_element, label_element in train_dataset:  
    print("Input:", input_element)  
    print("Label:", label_element)
    print(type(label_element["rating"]),label_element["rating"])
    print(label_element["rating"].numpy())
    break


Input: {'user_id': <tf.Tensor: shape=(), dtype=int64, numpy=1>, 'item_id': <tf.Tensor: shape=(), dtype=int64, numpy=48>, 'timestamp': <tf.Tensor: shape=(), dtype=int64, numpy=978824351>, 'title': <tf.Tensor: shape=(), dtype=string, numpy=b'Pocahontas (1995)'>, 'genres': <tf.Tensor: shape=(), dtype=string, numpy=b"Animation|Children's|Musical|Romance">, 'gender': <tf.Tensor: shape=(), dtype=string, numpy=b'F'>, 'age': <tf.Tensor: shape=(), dtype=int64, numpy=1>, 'occupation': <tf.Tensor: shape=(), dtype=int64, numpy=10>, 'zip': <tf.Tensor: shape=(), dtype=string, numpy=b'48067'>, 'itemid_seq': <tf.Tensor: shape=(), dtype=string, numpy=b'48|1907|783|1|527'>, 'itemid_seq_len': <tf.Tensor: shape=(), dtype=int64, numpy=5>}
Label: {'rating': <tf.Tensor: shape=(), dtype=int64, numpy=5>}
<class 'tensorflow.python.framework.ops.EagerTensor'> tf.Tensor(5, shape=(), dtype=int64)
5
